// migrate — orchestrates the fetch → transform → SQL output migration loop
package main

import (
	"log"
	"os"
	"strings"
	"time"
)

const requestDelayMs = 200

// MigrateToMarkdown converts all LEGACY posts to MARKDOWN and writes UPDATE statements
// to outputFile. When dryRun is true, transformation is performed but no file is written.
func MigrateToMarkdown(posts []legacyPost, dryRun bool, outputFile string) {
	log.Printf("found %d LEGACY NOTICE posts to migrate", len(posts))

	var sqlBuf strings.Builder
	sqlBuf.WriteString("-- Markdown migration: generated by migrate_to_md\n\n")

	success, failed := 0, 0
	for _, post := range posts {
		update, err := processPost(post)
		if err != nil {
			log.Printf("[SEQ %d] transform failed: %v", post.SEQ, err)
			failed++
		} else if dryRun {
			log.Printf("[DRY RUN][SEQ %d] %q → summary=%q", post.SEQ, post.Subject, update.Summary)
			success++
		} else {
			sqlBuf.WriteString(generateUpdateSQL(update))
			log.Printf("[SEQ %d] converted: %q", post.SEQ, post.Subject)
			success++
		}
		time.Sleep(requestDelayMs * time.Millisecond)
	}

	if !dryRun {
		if err := os.WriteFile(outputFile, []byte(sqlBuf.String()), 0644); err != nil {
			log.Fatalf("write SQL output: %v", err)
		}
		log.Printf("SQL written to %s (%d statements)", outputFile, success)
	}

	log.Printf("migration complete — success: %d, failed: %d", success, failed)
}
