-- Migration 001: Alter existing tables for social feed features
-- Target: MariaDB 10.1.38 (MyISAM tables — no engine change in Phase 1)

-- WEO_BOARDBBS: Add feed-related columns
ALTER TABLE WEO_BOARDBBS
  ADD COLUMN THUMBNAIL_URL VARCHAR(500) NULL COMMENT '대표 이미지 URL' AFTER FILES,
  ADD COLUMN SUMMARY VARCHAR(200) NULL COMMENT '본문 요약' AFTER THUMBNAIL_URL,
  ADD COLUMN IS_PINNED ENUM('Y','N') DEFAULT 'N' COMMENT '상단 고정 여부' AFTER SUMMARY;

-- MAIN_AD: Add ad tier and title label
ALTER TABLE MAIN_AD
  ADD COLUMN AD_TIER ENUM('PREMIUM','GOLD','NORMAL') DEFAULT 'NORMAL' COMMENT '광고 등급' AFTER MA_TYPE,
  ADD COLUMN AD_TITLE_LABEL VARCHAR(50) DEFAULT '추천 동문 소식' COMMENT '광고 카드 타이틀 라벨' AFTER AD_TIER;

-- FUNDAMENTAL_MEMBER: Add search indexes
CREATE INDEX INDX_COMPANY ON FUNDAMENTAL_MEMBER (FM_COMPANY);
CREATE INDEX INDX_POSITION ON FUNDAMENTAL_MEMBER (FM_POSITION);
