-- Migration 002: Create new InnoDB tables
-- Target: MariaDB 10.1.38

CREATE TABLE IF NOT EXISTS DONATION_SNAPSHOT (
    DS_SEQ        INT AUTO_INCREMENT PRIMARY KEY,
    DS_DATE       DATE NOT NULL,
    DS_TOTAL      BIGINT DEFAULT 0 NOT NULL,
    DS_MANUAL_ADJ BIGINT DEFAULT 0 NOT NULL,
    DS_DONOR_CNT  INT DEFAULT 0 NOT NULL,
    DS_GOAL       BIGINT DEFAULT 0 NOT NULL,
    REG_DATE      DATETIME NULL,
    UNIQUE KEY UK_DATE (DS_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DONATION_CONFIG (
    DC_SEQ        INT AUTO_INCREMENT PRIMARY KEY,
    DC_GOAL       BIGINT DEFAULT 0 NOT NULL,
    DC_MANUAL_ADJ BIGINT DEFAULT 0 NOT NULL,
    DC_NOTE       VARCHAR(200) NULL,
    IS_ACTIVE     ENUM('Y','N') DEFAULT 'Y',
    REG_DATE      DATETIME NULL,
    REG_OPER      INT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_SESSION (
    SESSION_ID    VARCHAR(64) NOT NULL PRIMARY KEY,
    USR_SEQ       INT NOT NULL,
    PROVIDER      ENUM('KAKAO','DIRECT') DEFAULT 'DIRECT',
    EXPIRES_AT    DATETIME NOT NULL,
    CREATED_AT    DATETIME NOT NULL,
    INDEX IDX_USR (USR_SEQ),
    INDEX IDX_EXPIRES (EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WEO_AD_LOG (
    AL_SEQ     INT AUTO_INCREMENT PRIMARY KEY,
    MA_SEQ     INT NOT NULL,
    USR_SEQ    INT NULL,
    AL_TYPE    ENUM('VIEW','CLICK') NOT NULL,
    AL_DATE    DATETIME NOT NULL,
    AL_IPADDR  VARCHAR(45) NULL,
    INDEX IDX_MA_SEQ (MA_SEQ),
    INDEX IDX_DATE (AL_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
