-- Migration 009: Create alumni message table for direct messaging
-- Target: MariaDB 10.1.38

CREATE TABLE ALUMNI_MESSAGE (
    AM_SEQ        INT AUTO_INCREMENT PRIMARY KEY,
    AM_SENDER_SEQ INT NOT NULL,
    AM_RECVR_SEQ  INT NOT NULL,
    AM_CONTENT    TEXT NOT NULL,
    AM_READ_YN    ENUM('Y','N') DEFAULT 'N',
    AM_DEL_SENDER ENUM('Y','N') DEFAULT 'N',
    AM_DEL_RECVR  ENUM('Y','N') DEFAULT 'N',
    REG_DATE      DATETIME NULL,
    READ_DATE     DATETIME NULL,
    INDEX IDX_SENDER (AM_SENDER_SEQ, REG_DATE),
    INDEX IDX_RECVR (AM_RECVR_SEQ, AM_READ_YN, REG_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
