-- Migration 010: Create subscription table for recurring donations

CREATE TABLE SUBSCRIPTION (
  SUB_SEQ INT AUTO_INCREMENT PRIMARY KEY,
  USR_SEQ INT NOT NULL,
  AMOUNT INT NOT NULL,
  PAY_TYPE VARCHAR(10) NOT NULL DEFAULT 'CARD',
  STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
  START_DATE DATETIME NOT NULL,
  NEXT_BILL DATETIME NOT NULL,
  REG_DATE DATETIME NOT NULL,
  EDT_DATE DATETIME,
  INDEX idx_usr_seq (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
