-- 011_add_ad_like_table.sql
-- Creates WEO_AD_LIKE table for ad like engagement.

CREATE TABLE IF NOT EXISTS WEO_AD_LIKE (
    AL_SEQ   INT AUTO_INCREMENT PRIMARY KEY,
    MA_SEQ   INT NOT NULL,
    USR_SEQ  INT NOT NULL,
    OPEN_YN  ENUM('Y','N') NOT NULL DEFAULT 'Y',
    REG_DATE DATETIME NOT NULL,
    INDEX IDX_MA_USR (MA_SEQ, USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
