-- 012_add_ad_comment_table.sql
-- Creates WEO_AD_COMMENT table for ad comment engagement.

CREATE TABLE IF NOT EXISTS WEO_AD_COMMENT (
    AC_SEQ   INT AUTO_INCREMENT PRIMARY KEY,
    MA_SEQ   INT NOT NULL,
    USR_SEQ  INT NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    CONTENTS TEXT NOT NULL,
    OPEN_YN  ENUM('Y','N') NOT NULL DEFAULT 'Y',
    REG_DATE DATETIME NOT NULL,
    INDEX IDX_MA_SEQ (MA_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
