-- 016_create_password_reset_table.sql — Creates ALUMNI_PASSWORD_RESET for email-based password recovery

CREATE TABLE ALUMNI_PASSWORD_RESET (
    APR_SEQ      INT AUTO_INCREMENT PRIMARY KEY,
    USR_SEQ      INT NOT NULL,
    APR_TOKEN    VARCHAR(64) NOT NULL,
    APR_USED_YN  ENUM('Y','N') DEFAULT 'N',
    EXPIRES_AT   DATETIME NOT NULL,
    REG_DATE     DATETIME NULL,
    UNIQUE INDEX IDX_TOKEN (APR_TOKEN),
    INDEX IDX_USR (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
