-- 017_create_notification_table.sql — Create ALUMNI_NOTIFICATION table for in-app notifications

CREATE TABLE IF NOT EXISTS ALUMNI_NOTIFICATION (
    AN_SEQ       INT AUTO_INCREMENT PRIMARY KEY,
    USR_SEQ      INT NOT NULL,
    AN_TYPE      VARCHAR(30) NOT NULL,
    AN_TITLE     VARCHAR(200) NOT NULL,
    AN_BODY      VARCHAR(500) NULL,
    AN_REF_SEQ   INT NULL,
    AN_READ_YN   ENUM('Y','N') DEFAULT 'N',
    REG_DATE     DATETIME NULL,
    INDEX IDX_USR_READ (USR_SEQ, AN_READ_YN, REG_DATE),
    INDEX IDX_USR_DATE (USR_SEQ, REG_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
