-- Migration 020: Add overwrite flag to donation config and snapshot
ALTER TABLE DONATION_CONFIG
  ADD COLUMN DC_OVERWRITE ENUM('Y','N') NOT NULL DEFAULT 'N';

ALTER TABLE DONATION_SNAPSHOT
  ADD COLUMN DS_OVERWRITE ENUM('Y','N') NOT NULL DEFAULT 'N';
