-- 022_extend_subscription_billing.sql — Add billing-key, BILL_DAY, end-month, last-billed, fail-count, order-link columns to SUBSCRIPTION

ALTER TABLE SUBSCRIPTION
  ADD COLUMN BILLING_KEY    VARCHAR(64) NULL AFTER PAY_TYPE,
  ADD COLUMN CARD_NO        VARCHAR(32) NULL AFTER BILLING_KEY,
  ADD COLUMN BILL_DAY       TINYINT     NULL AFTER NEXT_BILL,
  ADD COLUMN END_YYYYMM     CHAR(6)     NULL AFTER BILL_DAY,
  ADD COLUMN LAST_BILLED_AT DATETIME    NULL AFTER END_YYYYMM,
  ADD COLUMN FAIL_COUNT     INT NOT NULL DEFAULT 0 AFTER LAST_BILLED_AT,
  ADD COLUMN ORDER_SEQ      INT         NULL AFTER FAIL_COUNT;

ALTER TABLE SUBSCRIPTION
  ADD INDEX idx_bill_day_status (BILL_DAY, STATUS),
  ADD INDEX idx_order_seq (ORDER_SEQ);
