-- 030_create_mobile_refresh_token_table.sql — Refresh-token one-time usage tracking
CREATE TABLE IF NOT EXISTS ALUMNI_MOBILE_REFRESH_TOKEN (
    MRT_JTI       VARCHAR(64) NOT NULL PRIMARY KEY,
    USR_SEQ       INT NOT NULL,
    MRT_SID       VARCHAR(64) NOT NULL,
    EXPIRES_AT    DATETIME NOT NULL,
    CREATED_AT    DATETIME NOT NULL,
    MRT_REVOKED_AT DATETIME NULL,
    INDEX IDX_USR (USR_SEQ),
    INDEX IDX_EXPIRES (EXPIRES_AT),
    INDEX IDX_REVOKED (MRT_REVOKED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
