-- 034_create_push_outbox.sql — Durable iOS push delivery outbox

CREATE TABLE IF NOT EXISTS ALUMNI_PUSH_OUTBOX (
    PO_SEQ            INT AUTO_INCREMENT PRIMARY KEY,
    EVENT_TYPE        VARCHAR(64) NOT NULL,
    EVENT_ID          VARCHAR(191) NOT NULL,
    USR_SEQ           INT NOT NULL,
    MDT_SEQ           INT NOT NULL,
    DEVICE_TOKEN      VARCHAR(512) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    APNS_ENVIRONMENT  ENUM('sandbox','production') NOT NULL DEFAULT 'production',
    BUNDLE_ID         VARCHAR(255) NULL,
    TITLE             VARCHAR(255) NOT NULL,
    BODY              VARCHAR(1000) NOT NULL,
    PAYLOAD_JSON      LONGTEXT NOT NULL,
    STATUS            ENUM('PENDING','PROCESSING','SENT','FAILED','DEAD') NOT NULL DEFAULT 'PENDING',
    ATTEMPT_COUNT     INT NOT NULL DEFAULT 0,
    NEXT_ATTEMPT_AT   DATETIME NOT NULL,
    LAST_ERROR_CODE   VARCHAR(128) NULL,
    LAST_ERROR_MESSAGE VARCHAR(1000) NULL,
    CLAIM_TOKEN       VARCHAR(64) NULL,
    CREATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    SENT_AT           DATETIME NULL,
    UNIQUE KEY UK_PUSH_OUTBOX_EVENT_TOKEN (EVENT_ID, MDT_SEQ),
    INDEX IDX_PUSH_OUTBOX_DUE (STATUS, NEXT_ATTEMPT_AT),
    INDEX IDX_PUSH_OUTBOX_CLAIM (CLAIM_TOKEN),
    INDEX IDX_PUSH_OUTBOX_CREATED (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
