-- 035_create_push_preference.sql — Per-user mobile push notification preferences

CREATE TABLE IF NOT EXISTS ALUMNI_PUSH_PREFERENCE (
    USR_SEQ         INT PRIMARY KEY,
    NOTICE_ENABLED  ENUM('Y','N') NOT NULL DEFAULT 'Y',
    MESSAGE_ENABLED ENUM('Y','N') NOT NULL DEFAULT 'Y',
    CREATED_AT      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_PUSH_PREFERENCE_NOTICE (NOTICE_ENABLED),
    INDEX IDX_PUSH_PREFERENCE_MESSAGE (MESSAGE_ENABLED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
