-- Migration 038: Separate canonical administrator role and alumni verification.
-- Target: MariaDB 10.1.38. Apply after a backup.
-- Legacy mapping is preserved exactly:
--   BAA -> rejected, BBB -> pending, CCC/ZZZ -> approved, ZZZ -> root.

CREATE TABLE IF NOT EXISTS ALUMNI_ADMIN_ROLE (
    USR_SEQ       INT NOT NULL PRIMARY KEY,
    ADMIN_ROLE    ENUM('root','operator') NOT NULL,
    CREATED_AT    DATETIME NOT NULL,
    UPDATED_AT    DATETIME NOT NULL,
    CREATED_BY    INT NULL,
    UPDATED_BY    INT NULL,
    INDEX IDX_AAR_ROLE (ADMIN_ROLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ALUMNI_VERIFICATION (
    USR_SEQ                     INT NOT NULL PRIMARY KEY,
    STATUS                      ENUM('unsubmitted','pending','rejected','approved','reapproval_pending') NOT NULL,
    GRADUATION_YEAR             SMALLINT UNSIGNED NULL,
    COHORT                      VARCHAR(20) NULL,
    DEPARTMENT                  VARCHAR(100) NULL,
    REJECTION_REASON            VARCHAR(500) NULL,
    SUBMITTED_AT                DATETIME NULL,
    REVIEWED_AT                 DATETIME NULL,
    REVIEWED_BY                 INT NULL,
    APPROVED_GRADUATION_YEAR    SMALLINT UNSIGNED NULL,
    APPROVED_COHORT             VARCHAR(20) NULL,
    APPROVED_DEPARTMENT         VARCHAR(100) NULL,
    CREATED_AT                  DATETIME NOT NULL,
    UPDATED_AT                  DATETIME NOT NULL,
    INDEX IDX_AV_STATUS_UPDATED (STATUS, UPDATED_AT),
    INDEX IDX_AV_REVIEWER (REVIEWED_BY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO ALUMNI_ADMIN_ROLE (
    USR_SEQ, ADMIN_ROLE, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
)
SELECT USR_SEQ, 'root', NOW(), NOW(), USR_SEQ, USR_SEQ
FROM WEO_MEMBER
WHERE USR_STATUS = 'ZZZ';

INSERT IGNORE INTO ALUMNI_VERIFICATION (
    USR_SEQ,
    STATUS,
    GRADUATION_YEAR,
    COHORT,
    DEPARTMENT,
    REJECTION_REASON,
    SUBMITTED_AT,
    REVIEWED_AT,
    REVIEWED_BY,
    APPROVED_GRADUATION_YEAR,
    APPROVED_COHORT,
    APPROVED_DEPARTMENT,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    USR_SEQ,
    CASE
        WHEN USR_STATUS = 'BAA' THEN 'rejected'
        WHEN USR_STATUS = 'BBB' THEN 'pending'
        ELSE 'approved'
    END,
    NULL,
    NULLIF(TRIM(USR_FN), ''),
    NULLIF(TRIM(USR_DEPT), ''),
    CASE WHEN USR_STATUS = 'BAA' THEN '기존 회원 상태로 인해 반려됨' ELSE NULL END,
    NULL,
    NULL,
    NULL,
    NULL,
    CASE WHEN USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(USR_FN), '') ELSE NULL END,
    CASE WHEN USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(USR_DEPT), '') ELSE NULL END,
    NOW(),
    NOW()
FROM WEO_MEMBER
WHERE USR_STATUS IN ('BAA','BBB','CCC','ZZZ');

DROP TRIGGER IF EXISTS TRG_WEO_MEMBER_AUTH_PRINCIPAL_INSERT;
DROP TRIGGER IF EXISTS TRG_WEO_MEMBER_AUTH_PRINCIPAL_UPDATE;

DELIMITER //
CREATE TRIGGER TRG_WEO_MEMBER_AUTH_PRINCIPAL_INSERT
AFTER INSERT ON WEO_MEMBER
FOR EACH ROW
BEGIN
    IF NEW.USR_STATUS IN ('BAA','BBB','CCC','ZZZ') THEN
        INSERT INTO ALUMNI_VERIFICATION (
            USR_SEQ, STATUS, COHORT, DEPARTMENT, REJECTION_REASON,
            APPROVED_COHORT, APPROVED_DEPARTMENT, CREATED_AT, UPDATED_AT
        ) VALUES (
            NEW.USR_SEQ,
            CASE
                WHEN NEW.USR_STATUS = 'BAA' THEN 'rejected'
                WHEN NEW.USR_STATUS = 'BBB' THEN 'pending'
                ELSE 'approved'
            END,
            NULLIF(TRIM(NEW.USR_FN), ''),
            NULLIF(TRIM(NEW.USR_DEPT), ''),
            CASE WHEN NEW.USR_STATUS = 'BAA' THEN '기존 회원 상태로 인해 반려됨' ELSE NULL END,
            CASE WHEN NEW.USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(NEW.USR_FN), '') ELSE NULL END,
            CASE WHEN NEW.USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(NEW.USR_DEPT), '') ELSE NULL END,
            NOW(), NOW()
        );
    END IF;
    IF NEW.USR_STATUS = 'ZZZ' THEN
        INSERT INTO ALUMNI_ADMIN_ROLE (
            USR_SEQ, ADMIN_ROLE, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
        ) VALUES (NEW.USR_SEQ, 'root', NOW(), NOW(), NEW.USR_SEQ, NEW.USR_SEQ);
    END IF;
END //

CREATE TRIGGER TRG_WEO_MEMBER_AUTH_PRINCIPAL_UPDATE
AFTER UPDATE ON WEO_MEMBER
FOR EACH ROW
BEGIN
    IF NOT (NEW.USR_STATUS <=> OLD.USR_STATUS) AND NEW.USR_STATUS IN ('BAA','BBB','CCC','ZZZ') THEN
        INSERT INTO ALUMNI_VERIFICATION (
            USR_SEQ, STATUS, COHORT, DEPARTMENT, REJECTION_REASON,
            APPROVED_COHORT, APPROVED_DEPARTMENT, CREATED_AT, UPDATED_AT
        ) VALUES (
            NEW.USR_SEQ,
            CASE
                WHEN NEW.USR_STATUS = 'BAA' THEN 'rejected'
                WHEN NEW.USR_STATUS = 'BBB' THEN 'pending'
                ELSE 'approved'
            END,
            NULLIF(TRIM(NEW.USR_FN), ''),
            NULLIF(TRIM(NEW.USR_DEPT), ''),
            CASE WHEN NEW.USR_STATUS = 'BAA' THEN '기존 회원 상태로 인해 반려됨' ELSE NULL END,
            CASE WHEN NEW.USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(NEW.USR_FN), '') ELSE NULL END,
            CASE WHEN NEW.USR_STATUS IN ('CCC','ZZZ') THEN NULLIF(TRIM(NEW.USR_DEPT), '') ELSE NULL END,
            NOW(), NOW()
        ) ON DUPLICATE KEY UPDATE
            STATUS = VALUES(STATUS),
            COHORT = VALUES(COHORT),
            DEPARTMENT = VALUES(DEPARTMENT),
            REJECTION_REASON = VALUES(REJECTION_REASON),
            APPROVED_COHORT = VALUES(APPROVED_COHORT),
            APPROVED_DEPARTMENT = VALUES(APPROVED_DEPARTMENT),
            UPDATED_AT = NOW();
    END IF;
    IF NOT (NEW.USR_STATUS <=> OLD.USR_STATUS) THEN
        IF NEW.USR_STATUS = 'ZZZ' THEN
            INSERT INTO ALUMNI_ADMIN_ROLE (
                USR_SEQ, ADMIN_ROLE, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY
            ) VALUES (NEW.USR_SEQ, 'root', NOW(), NOW(), NEW.USR_SEQ, NEW.USR_SEQ)
            ON DUPLICATE KEY UPDATE
                ADMIN_ROLE = 'root', UPDATED_AT = NOW(), UPDATED_BY = NEW.USR_SEQ;
        ELSE
            DELETE FROM ALUMNI_ADMIN_ROLE
            WHERE USR_SEQ = NEW.USR_SEQ AND ADMIN_ROLE = 'root';
        END IF;
    END IF;
END //
DELIMITER ;
