-- Migration 039: Durable, one-time mobile social-link continuations and reauthentication guards.
-- Target: MariaDB 10.1.38. Raw link tokens and provider credentials are never stored.

CREATE TABLE IF NOT EXISTS ALUMNI_SOCIAL_LINK_REAUTH_GUARD (
    SLR_PROVIDER        VARCHAR(20) NOT NULL,
    SLR_SUBJECT         VARCHAR(191) NOT NULL,
    SLR_FAILED_ATTEMPTS INT NOT NULL DEFAULT 0,
    SLR_LOCKED_AT       DATETIME NULL,
    SLR_EXPIRES_AT      DATETIME NOT NULL,
    SLR_UPDATED_AT      DATETIME NOT NULL,
    PRIMARY KEY (SLR_PROVIDER, SLR_SUBJECT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ALUMNI_SOCIAL_LINK_CONTINUATION (
    SLC_TOKEN_HASH   CHAR(64) NOT NULL PRIMARY KEY,
    SLC_PROVIDER     VARCHAR(20) NOT NULL,
    SLC_SUBJECT      VARCHAR(191) NOT NULL,
    SLC_EMAIL        VARCHAR(255) NULL,
    SLC_STATUS       ENUM('READY','CONSUMED') NOT NULL DEFAULT 'READY',
    SLC_EXPIRES_AT   DATETIME NOT NULL,
    SLC_CONSUMED_AT  DATETIME NULL,
    SLC_CREATED_AT   DATETIME NOT NULL,
    INDEX IDX_SLC_STATUS_EXPIRY (SLC_STATUS, SLC_EXPIRES_AT),
    INDEX IDX_SLC_PROVIDER_SUBJECT (SLC_PROVIDER, SLC_SUBJECT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rollback (only after reverting the application binary):
-- DROP TABLE ALUMNI_SOCIAL_LINK_CONTINUATION;
-- DROP TABLE ALUMNI_SOCIAL_LINK_REAUTH_GUARD;
