-- Migration 041: Create the canonical account-state and identity authority.
-- Deferred after a planning change: unapplied in production; future application timing will be decided separately.
-- Target: MariaDB 10.1.38. Apply only after migration 040 converted WEO_MEMBER to InnoDB.
-- Provider subjects and verified EMAIL login identities are global authorities.
-- Profile/provider metadata is non-authoritative and must never be used for automatic linking.

CREATE TABLE AUTH_ACCOUNT_STATE (
    ACCOUNT_ID  INT NOT NULL,
    STATUS      ENUM('ACTIVE','SUSPENDED','WITHDRAWN') NOT NULL,
    SUSPENDED_AT DATETIME NULL,
    WITHDRAWN_AT DATETIME NULL,
    CREATED_AT  DATETIME NOT NULL,
    UPDATED_AT  DATETIME NOT NULL,
    PRIMARY KEY (ACCOUNT_ID),
    INDEX IDX_AUTH_ACCOUNT_STATE_STATUS (STATUS, UPDATED_AT),
    CONSTRAINT FK_AUTH_ACCOUNT_STATE_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES WEO_MEMBER (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_IDENTITY (
    IDENTITY_ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID           INT NOT NULL,
    PROVIDER             ENUM('EMAIL','KAKAO','APPLE','LOCAL_USERNAME') NOT NULL,
    SUBJECT_KEY          VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    NORMALIZED_EMAIL     VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
    STATUS               ENUM('ACTIVE','DISABLED','REVOKED') NOT NULL,
    METADATA_TEXT        TEXT NULL,
    VERIFIED_AT          DATETIME NULL,
    LAST_AUTHENTICATED_AT DATETIME NULL,
    REVOKED_AT           DATETIME NULL,
    CREATED_AT           DATETIME NOT NULL,
    UPDATED_AT           DATETIME NOT NULL,
    PRIMARY KEY (IDENTITY_ID),
    UNIQUE KEY UQ_AUTH_IDENTITY_PROVIDER_SUBJECT (PROVIDER, SUBJECT_KEY),
    UNIQUE KEY UQ_AUTH_IDENTITY_NORMALIZED_EMAIL (NORMALIZED_EMAIL),
    UNIQUE KEY UQ_AUTH_IDENTITY_ID_ACCOUNT (IDENTITY_ID, ACCOUNT_ID),
    UNIQUE KEY UQ_AUTH_IDENTITY_ID_PROVIDER (IDENTITY_ID, PROVIDER),
    UNIQUE KEY UQ_AUTH_IDENTITY_ID_ACCOUNT_PROVIDER (IDENTITY_ID, ACCOUNT_ID, PROVIDER),
    INDEX IDX_AUTH_IDENTITY_ACCOUNT_STATUS (ACCOUNT_ID, STATUS),
    CONSTRAINT FK_AUTH_IDENTITY_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES WEO_MEMBER (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_EMAIL_VERIFICATION (
    TOKEN_HASH       CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    NORMALIZED_EMAIL VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS           ENUM('READY','CONSUMED','CANCELLED','EXPIRED') NOT NULL,
    ATTEMPT_COUNT    INT UNSIGNED NOT NULL DEFAULT 0,
    EXPIRES_AT       DATETIME NOT NULL,
    CONSUMED_AT      DATETIME NULL,
    CANCELLED_AT     DATETIME NULL,
    CREATED_AT       DATETIME NOT NULL,
    PRIMARY KEY (TOKEN_HASH),
    INDEX IDX_AUTH_EMAIL_VERIFICATION_EMAIL_STATUS (
        NORMALIZED_EMAIL, STATUS, EXPIRES_AT
    ),
    INDEX IDX_AUTH_EMAIL_VERIFICATION_STATUS_EXPIRY (STATUS, EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_SIGNUP_CONTINUATION (
    TOKEN_HASH    CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PROVIDER      ENUM('EMAIL','KAKAO','APPLE') NOT NULL,
    SUBJECT_KEY   VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS        ENUM('READY','CONSUMED','CANCELLED','EXPIRED') NOT NULL,
    PREFILL_TEXT  TEXT NULL,
    EXPIRES_AT    DATETIME NOT NULL,
    CONSUMED_AT   DATETIME NULL,
    CANCELLED_AT  DATETIME NULL,
    CREATED_AT    DATETIME NOT NULL,
    PRIMARY KEY (TOKEN_HASH),
    UNIQUE KEY UQ_AUTH_SIGNUP_CONTINUATION_TOKEN_PROVIDER (TOKEN_HASH, PROVIDER),
    INDEX IDX_AUTH_SIGNUP_CONTINUATION_SUBJECT_STATUS (
        PROVIDER, SUBJECT_KEY, STATUS, EXPIRES_AT
    ),
    INDEX IDX_AUTH_SIGNUP_CONTINUATION_STATUS_EXPIRY (STATUS, EXPIRES_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_PASSWORD_CREDENTIAL (
    IDENTITY_ID     BIGINT UNSIGNED NOT NULL,
    PROVIDER        ENUM('EMAIL','KAKAO','APPLE','LOCAL_USERNAME') NOT NULL,
    ALGORITHM       VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PARAMETERS_TEXT VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PASSWORD_HASH   VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS          ENUM('ACTIVE','DISABLED') NOT NULL,
    CREATED_AT      DATETIME NOT NULL,
    UPDATED_AT      DATETIME NOT NULL,
    PRIMARY KEY (IDENTITY_ID),
    CONSTRAINT FK_AUTH_PASSWORD_CREDENTIAL_IDENTITY
        FOREIGN KEY (IDENTITY_ID, PROVIDER)
        REFERENCES AUTH_IDENTITY (IDENTITY_ID, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_PROVIDER_CREDENTIAL (
    CREDENTIAL_ID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDENTITY_ID             BIGINT UNSIGNED NULL,
    CONTINUATION_TOKEN_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    PROVIDER                ENUM('EMAIL','KAKAO','APPLE','LOCAL_USERNAME') NOT NULL,
    KEY_ID                  VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    NONCE_BYTES             VARBINARY(32) NOT NULL,
    ALGORITHM               VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    CIPHERTEXT              BLOB NOT NULL,
    CREATED_AT              DATETIME NOT NULL,
    UPDATED_AT              DATETIME NOT NULL,
    REVOKED_AT              DATETIME NULL,
    PRIMARY KEY (CREDENTIAL_ID),
    UNIQUE KEY UQ_AUTH_PROVIDER_CREDENTIAL_IDENTITY (IDENTITY_ID),
    UNIQUE KEY UQ_AUTH_PROVIDER_CREDENTIAL_CONTINUATION (CONTINUATION_TOKEN_HASH),
    UNIQUE KEY UQ_AUTH_PROVIDER_CREDENTIAL_ID_OWNER (CREDENTIAL_ID, IDENTITY_ID, PROVIDER),
    CONSTRAINT FK_AUTH_PROVIDER_CREDENTIAL_IDENTITY
        FOREIGN KEY (IDENTITY_ID, PROVIDER)
        REFERENCES AUTH_IDENTITY (IDENTITY_ID, PROVIDER),
    CONSTRAINT FK_AUTH_PROVIDER_CREDENTIAL_CONTINUATION
        FOREIGN KEY (CONTINUATION_TOKEN_HASH, PROVIDER)
        REFERENCES AUTH_SIGNUP_CONTINUATION (TOKEN_HASH, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_CONSENT (
    CONSENT_ID      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID      INT NOT NULL,
    CONSENT_TYPE    ENUM('TERMS','PRIVACY','MARKETING') NOT NULL,
    CONSENT_VERSION VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    IS_REQUIRED     TINYINT(1) NOT NULL,
    IS_ACCEPTED     TINYINT(1) NOT NULL,
    ACCEPTED_AT     DATETIME NULL,
    WITHDRAWN_AT    DATETIME NULL,
    CREATED_AT      DATETIME NOT NULL,
    PRIMARY KEY (CONSENT_ID),
    UNIQUE KEY UQ_AUTH_CONSENT_ACCOUNT_TYPE_VERSION (
        ACCOUNT_ID, CONSENT_TYPE, CONSENT_VERSION
    ),
    INDEX IDX_AUTH_CONSENT_ACCOUNT_CREATED (ACCOUNT_ID, CREATED_AT),
    CONSTRAINT FK_AUTH_CONSENT_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES WEO_MEMBER (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_SESSION_FAMILY (
    FAMILY_ID         CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    ACCOUNT_ID        INT NOT NULL,
    IDENTITY_ID       BIGINT UNSIGNED NOT NULL,
    AUTH_METHOD       ENUM('EMAIL','KAKAO','APPLE','LOCAL_USERNAME') NOT NULL,
    GENERATION        BIGINT UNSIGNED NOT NULL,
    STATUS            ENUM('ACTIVE','REVOKED','EXPIRED') NOT NULL,
    EXPIRES_AT        DATETIME NOT NULL,
    LAST_ROTATED_AT   DATETIME NULL,
    REVOKED_AT        DATETIME NULL,
    REVOKE_REASON_CODE VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    CREATED_AT        DATETIME NOT NULL,
    UPDATED_AT        DATETIME NOT NULL,
    PRIMARY KEY (FAMILY_ID),
    INDEX IDX_AUTH_SESSION_FAMILY_ACCOUNT_STATUS (ACCOUNT_ID, STATUS),
    INDEX IDX_AUTH_SESSION_FAMILY_IDENTITY_STATUS (IDENTITY_ID, STATUS),
    CONSTRAINT FK_AUTH_SESSION_FAMILY_ACCOUNT
        FOREIGN KEY (ACCOUNT_ID) REFERENCES WEO_MEMBER (USR_SEQ),
    CONSTRAINT FK_AUTH_SESSION_FAMILY_IDENTITY_ACCOUNT
        FOREIGN KEY (IDENTITY_ID, ACCOUNT_ID, AUTH_METHOD)
        REFERENCES AUTH_IDENTITY (IDENTITY_ID, ACCOUNT_ID, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_PROVIDER_REVOKE_OUTBOX (
    OUTBOX_ID        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    IDEMPOTENCY_KEY  CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    ACCOUNT_ID       INT NOT NULL,
    IDENTITY_ID      BIGINT UNSIGNED NOT NULL,
    CREDENTIAL_ID    BIGINT UNSIGNED NULL,
    PROVIDER         ENUM('EMAIL','KAKAO','APPLE','LOCAL_USERNAME') NOT NULL,
    STATUS           ENUM('PENDING','PROCESSING','DELIVERED','FAILED') NOT NULL,
    ATTEMPT_COUNT    INT UNSIGNED NOT NULL,
    NEXT_ATTEMPT_AT  DATETIME NOT NULL,
    LOCKED_AT        DATETIME NULL,
    DELIVERED_AT     DATETIME NULL,
    LAST_ERROR_CODE  VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    CREATED_AT       DATETIME NOT NULL,
    UPDATED_AT       DATETIME NOT NULL,
    PRIMARY KEY (OUTBOX_ID),
    UNIQUE KEY UQ_AUTH_PROVIDER_REVOKE_IDEMPOTENCY (IDEMPOTENCY_KEY),
    INDEX IDX_AUTH_PROVIDER_REVOKE_DELIVERY (STATUS, NEXT_ATTEMPT_AT, OUTBOX_ID),
    CONSTRAINT FK_AUTH_PROVIDER_REVOKE_IDENTITY_ACCOUNT
        FOREIGN KEY (IDENTITY_ID, ACCOUNT_ID, PROVIDER)
        REFERENCES AUTH_IDENTITY (IDENTITY_ID, ACCOUNT_ID, PROVIDER),
    CONSTRAINT FK_AUTH_PROVIDER_REVOKE_CREDENTIAL
        FOREIGN KEY (CREDENTIAL_ID, IDENTITY_ID, PROVIDER)
        REFERENCES AUTH_PROVIDER_CREDENTIAL (CREDENTIAL_ID, IDENTITY_ID, PROVIDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELIMITER //
CREATE TRIGGER TRG_AUTH_PASSWORD_CREDENTIAL_PROVIDER_INSERT
BEFORE INSERT ON AUTH_PASSWORD_CREDENTIAL
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('EMAIL','LOCAL_USERNAME') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'password credential requires EMAIL or LOCAL_USERNAME';
    END IF;
END //

CREATE TRIGGER TRG_AUTH_PASSWORD_CREDENTIAL_PROVIDER_UPDATE
BEFORE UPDATE ON AUTH_PASSWORD_CREDENTIAL
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('EMAIL','LOCAL_USERNAME') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'password credential requires EMAIL or LOCAL_USERNAME';
    END IF;
END //

CREATE TRIGGER TRG_AUTH_PROVIDER_CREDENTIAL_OWNER_INSERT
BEFORE INSERT ON AUTH_PROVIDER_CREDENTIAL
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('KAKAO','APPLE') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential requires KAKAO or APPLE';
    END IF;
    IF (NEW.IDENTITY_ID IS NULL AND NEW.CONTINUATION_TOKEN_HASH IS NULL)
       OR (NEW.IDENTITY_ID IS NOT NULL AND NEW.CONTINUATION_TOKEN_HASH IS NOT NULL) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential requires exactly one owner';
    END IF;
    IF OCTET_LENGTH(NEW.NONCE_BYTES) <> 12 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential nonce must be 12 bytes';
    END IF;
END //

CREATE TRIGGER TRG_AUTH_PROVIDER_CREDENTIAL_OWNER_UPDATE
BEFORE UPDATE ON AUTH_PROVIDER_CREDENTIAL
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('KAKAO','APPLE') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential requires KAKAO or APPLE';
    END IF;
    IF (NEW.IDENTITY_ID IS NULL AND NEW.CONTINUATION_TOKEN_HASH IS NULL)
       OR (NEW.IDENTITY_ID IS NOT NULL AND NEW.CONTINUATION_TOKEN_HASH IS NOT NULL) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential requires exactly one owner';
    END IF;
    IF OCTET_LENGTH(NEW.NONCE_BYTES) <> 12 THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider credential nonce must be 12 bytes';
    END IF;
END //

CREATE TRIGGER TRG_AUTH_PROVIDER_REVOKE_PROVIDER_INSERT
BEFORE INSERT ON AUTH_PROVIDER_REVOKE_OUTBOX
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('KAKAO','APPLE') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider revoke requires KAKAO or APPLE';
    END IF;
END //

CREATE TRIGGER TRG_AUTH_PROVIDER_REVOKE_PROVIDER_UPDATE
BEFORE UPDATE ON AUTH_PROVIDER_REVOKE_OUTBOX
FOR EACH ROW
BEGIN
    IF NEW.PROVIDER NOT IN ('KAKAO','APPLE') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'provider revoke requires KAKAO or APPLE';
    END IF;
END //
DELIMITER ;
