-- Migration 042: Prepare the canonical identity backfill run and journal authority.
-- Target: MariaDB 10.1.38.
-- This migration is additive only. It does not backfill data, remove legacy authority,
-- invalidate sessions, or alter canonical domain tables.

CREATE TABLE AUTH_IDENTITY_MIGRATION_RUN (
    RUN_ID             CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS             ENUM('PREFLIGHT_PASSED','APPLYING','APPLIED','FAILED') NOT NULL,
    SOURCE_FINGERPRINT CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    CONFLICT_COUNT     INT UNSIGNED NOT NULL,
    FAILURE_CODE       VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    STARTED_AT         DATETIME NOT NULL,
    COMPLETED_AT       DATETIME NULL,
    UPDATED_AT         DATETIME NOT NULL,
    PRIMARY KEY (RUN_ID),
    INDEX IDX_AUTH_IDENTITY_MIGRATION_RUN_STATUS (STATUS, UPDATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE AUTH_IDENTITY_MIGRATION_JOURNAL (
    RUN_ID       CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STEP_KEY     VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS       ENUM('STARTED','APPLIED','FAILED') NOT NULL,
    FAILURE_CODE VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
    STARTED_AT   DATETIME NOT NULL,
    APPLIED_AT   DATETIME NULL,
    UPDATED_AT   DATETIME NOT NULL,
    PRIMARY KEY (RUN_ID, STEP_KEY),
    INDEX IDX_AUTH_IDENTITY_MIGRATION_JOURNAL_STATUS (STATUS, UPDATED_AT),
    CONSTRAINT FK_AUTH_IDENTITY_MIGRATION_JOURNAL_RUN
        FOREIGN KEY (RUN_ID) REFERENCES AUTH_IDENTITY_MIGRATION_RUN (RUN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
