-- Migration 049: Add server-driven donation tree tier thresholds.
-- Target: MariaDB 10.1.38.

DELIMITER //
CREATE PROCEDURE IF NOT EXISTS _049_add_donation_tree_tier_thresholds_if_missing()
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'DONATION_CONFIG'
          AND COLUMN_NAME = 'DC_TIER_SPROUT_MIN'
    ) THEN
        ALTER TABLE DONATION_CONFIG
            ADD COLUMN DC_TIER_SPROUT_MIN BIGINT NOT NULL DEFAULT 1;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'DONATION_CONFIG'
          AND COLUMN_NAME = 'DC_TIER_SAPLING_MIN'
    ) THEN
        ALTER TABLE DONATION_CONFIG
            ADD COLUMN DC_TIER_SAPLING_MIN BIGINT NOT NULL DEFAULT 10000;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'DONATION_CONFIG'
          AND COLUMN_NAME = 'DC_TIER_TREE_MIN'
    ) THEN
        ALTER TABLE DONATION_CONFIG
            ADD COLUMN DC_TIER_TREE_MIN BIGINT NOT NULL DEFAULT 50000;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'DONATION_CONFIG'
          AND COLUMN_NAME = 'DC_TIER_BLOOMING_MIN'
    ) THEN
        ALTER TABLE DONATION_CONFIG
            ADD COLUMN DC_TIER_BLOOMING_MIN BIGINT NOT NULL DEFAULT 100000;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'DONATION_CONFIG'
          AND COLUMN_NAME = 'DC_TIER_FRUITING_MIN'
    ) THEN
        ALTER TABLE DONATION_CONFIG
            ADD COLUMN DC_TIER_FRUITING_MIN BIGINT NOT NULL DEFAULT 300000;
    END IF;
END //
DELIMITER ;

CALL _049_add_donation_tree_tier_thresholds_if_missing();

DROP PROCEDURE IF EXISTS _049_add_donation_tree_tier_thresholds_if_missing;

-- Rollback:
-- ALTER TABLE DONATION_CONFIG
--   DROP COLUMN DC_TIER_FRUITING_MIN,
--   DROP COLUMN DC_TIER_BLOOMING_MIN,
--   DROP COLUMN DC_TIER_TREE_MIN,
--   DROP COLUMN DC_TIER_SAPLING_MIN,
--   DROP COLUMN DC_TIER_SPROUT_MIN;
