-- 050_create_banner_ad.sql
-- Creates banner ad tables for sliding photo banner exposure and engagement logs.

CREATE TABLE IF NOT EXISTS MAIN_BANNER_AD (
    BN_SEQ        INT AUTO_INCREMENT PRIMARY KEY,
    BN_NAME       VARCHAR(200) NOT NULL,
    BN_URL        VARCHAR(500) NOT NULL,
    OPEN_YN       CHAR(1) NOT NULL DEFAULT 'N',
    INDX          INT NOT NULL DEFAULT 0,
    BN_START_DATE DATETIME NULL,
    BN_END_DATE   DATETIME NULL,
    CREATED_AT    DATETIME NOT NULL,
    UPDATED_AT    DATETIME NOT NULL,
    INDEX IDX_MBA_OPEN_YN (OPEN_YN),
    INDEX IDX_MBA_OPEN_PERIOD (OPEN_YN, BN_START_DATE, BN_END_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MAIN_BANNER_AD_IMAGE (
    BNI_SEQ     INT AUTO_INCREMENT PRIMARY KEY,
    BN_SEQ      INT NOT NULL,
    IMAGE_URL   VARCHAR(500) NOT NULL,
    SORT_ORDER  INT NOT NULL DEFAULT 0,
    INDEX IDX_MBAI_BN_SEQ (BN_SEQ),
    CONSTRAINT FK_MBAI_BN_SEQ
        FOREIGN KEY (BN_SEQ) REFERENCES MAIN_BANNER_AD (BN_SEQ)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WEO_BANNER_AD_LOG (
    BNL_SEQ     INT AUTO_INCREMENT PRIMARY KEY,
    BN_SEQ      INT NOT NULL,
    LOG_TYPE    ENUM('VIEW','CLICK') NOT NULL,
    CREATED_AT  DATETIME NOT NULL,
    INDEX IDX_WBAL_BN_SEQ (BN_SEQ),
    CONSTRAINT FK_WBAL_BN_SEQ
        FOREIGN KEY (BN_SEQ) REFERENCES MAIN_BANNER_AD (BN_SEQ)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
