-- Migration 053: Mobile application business-event collection.
-- Target: MariaDB 10.1.38.

CREATE TABLE IF NOT EXISTS ALUMNI_MOBILE_APP_EVENT (
    ID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLATFORM     VARCHAR(16) NOT NULL,
    EVENT_TYPE   VARCHAR(50) NOT NULL,
    USER_ID      INT NULL,
    APP_VERSION  VARCHAR(50) NOT NULL,
    OS_VERSION   VARCHAR(50) NOT NULL,
    DEVICE_MODEL VARCHAR(100) NULL,
    OCCURRED_AT  DATETIME NOT NULL,
    CREATED_AT   DATETIME NOT NULL,
    INDEX IDX_AME_PLATFORM (PLATFORM),
    INDEX IDX_AME_EVENT_TYPE (EVENT_TYPE),
    INDEX IDX_AME_OCCURRED_AT (OCCURRED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Rollback:
-- DROP TABLE ALUMNI_MOBILE_APP_EVENT;
