-- Durable manual account-deletion requests. MariaDB 10.1.38, additive only.
CREATE TABLE IF NOT EXISTS ALUMNI_ACCOUNT_DELETION_REQUEST (
    REQUEST_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USR_SEQ INT NULL,
    RECEIPT_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
    APPLE_REQUIRED TINYINT NOT NULL DEFAULT 0,
    KAKAO_REQUIRED TINYINT NOT NULL DEFAULT 0,
    REQUESTED_AT DATETIME NOT NULL,
    TARGET_AT DATETIME NOT NULL,
    DUE_AT DATETIME NOT NULL,
    COMPLETED_AT DATETIME NULL,
    OPERATOR_SEQ INT NULL,
    EVIDENCE_REFERENCE VARCHAR(1000) NOT NULL DEFAULT '',
    RETAINED_RECORDS VARCHAR(1000) NOT NULL DEFAULT '',
    RETENTION_UNTIL DATE NULL,
    UNIQUE KEY UK_ADR_USER (USR_SEQ),
    UNIQUE KEY UK_ADR_RECEIPT (RECEIPT_HASH),
    INDEX IDX_ADR_QUEUE (STATUS, DUE_AT),
    INDEX IDX_ADR_COMPLETE (COMPLETED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
