-- Automatic erasure state, restricted legal archives and durable file work.
-- MariaDB 10.1.38. No existing personal data is deleted by this migration.
CREATE TABLE IF NOT EXISTS ALUMNI_ACCOUNT_ERASURE (
    REQUEST_ID BIGINT NOT NULL PRIMARY KEY,
    MODE VARCHAR(10) NOT NULL DEFAULT 'automatic',
    STAGE VARCHAR(30) NOT NULL DEFAULT 'queued',
    LAST_CODE VARCHAR(80) NOT NULL DEFAULT '',
    NEXT_ATTEMPT_AT DATETIME NOT NULL,
    EXTERNAL_EVIDENCE VARCHAR(200) NOT NULL DEFAULT '',
    UPDATED_AT DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Preserve already accepted manual requests, including partially processed ones.
INSERT IGNORE INTO ALUMNI_ACCOUNT_ERASURE (REQUEST_ID,MODE,STAGE,NEXT_ATTEMPT_AT,UPDATED_AT)
SELECT REQUEST_ID,'manual','queued',UTC_TIMESTAMP(),UTC_TIMESTAMP()
FROM ALUMNI_ACCOUNT_DELETION_REQUEST WHERE STATUS <> 'completed';

CREATE TABLE IF NOT EXISTS ALUMNI_ERASURE_FILE (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    REQUEST_ID BIGINT NOT NULL,
    URL_PATH TEXT NOT NULL,
    URL_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    UNIQUE KEY UK_ERASURE_FILE (REQUEST_ID,URL_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ALUMNI_UPLOAD_OWNER (
    F_SEQ INT NOT NULL PRIMARY KEY,
    USR_SEQ INT NOT NULL,
    URL_PATH TEXT NOT NULL,
    KEY IDX_UPLOAD_OWNER (USR_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A reviewed, per-record decision, not a universal maximum retention period.
-- BASIS: ledger_10y / receipt_5y / external_original / erase.
CREATE TABLE IF NOT EXISTS ALUMNI_DONATION_RETENTION (
    O_SEQ INT NOT NULL PRIMARY KEY,
    BASIS VARCHAR(30) NOT NULL,
    BASIS_DATE DATE NULL,
    RETAIN_UNTIL DATE NULL,
    EVIDENCE_REFERENCE VARCHAR(200) NOT NULL,
    REVIEWED_AT DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- No public/member/admin listing API. Only the erasure worker writes archives.
-- Ciphertext uses a dedicated key; never copy member ID, phone, cohort or profile.
CREATE TABLE IF NOT EXISTS ALUMNI_DONATION_LEGAL_ARCHIVE (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BASIS VARCHAR(30) NOT NULL,
    RETAIN_UNTIL DATE NOT NULL,
    CIPHERTEXT MEDIUMBLOB NOT NULL,
    KEY IDX_LEGAL_EXPIRY (RETAIN_UNTIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Aggregate only: no order, donor, account, receipt, or transaction identifiers.
CREATE TABLE IF NOT EXISTS ALUMNI_ERASED_DONATION_TOTAL (
    ID TINYINT NOT NULL PRIMARY KEY,
    TOTAL_AMOUNT BIGINT NOT NULL DEFAULT 0,
    DONOR_COUNT BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO ALUMNI_ERASED_DONATION_TOTAL (ID) VALUES (1);
