-- Per-storage progress; missing evidence is never an exemption.
CREATE TABLE IF NOT EXISTS ALUMNI_ERASURE_TARGET (
 REQUEST_ID BIGINT NOT NULL,
 TARGET VARCHAR(30) NOT NULL,
 STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
 EVIDENCE_REFERENCE VARCHAR(200) NOT NULL DEFAULT '',
 LAST_CODE VARCHAR(80) NOT NULL DEFAULT '',
 ATTEMPTS INT NOT NULL DEFAULT 0,
 LAST_ATTEMPT_AT DATETIME NULL,
 UPDATED_AT DATETIME NOT NULL,
 PRIMARY KEY (REQUEST_ID,TARGET),
 CONSTRAINT FK_ERASURE_TARGET_REQUEST FOREIGN KEY (REQUEST_ID)
 REFERENCES ALUMNI_ACCOUNT_DELETION_REQUEST(REQUEST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO ALUMNI_ERASURE_TARGET (REQUEST_ID,TARGET,STATUS,EVIDENCE_REFERENCE,UPDATED_AT)
 SELECT e.REQUEST_ID,t.TARGET,
 CASE WHEN e.EXTERNAL_EVIDENCE<>'' OR d.STATUS='completed' THEN 'complete' ELSE 'pending' END,
 CASE WHEN e.EXTERNAL_EVIDENCE<>'' THEN e.EXTERNAL_EVIDENCE
 WHEN d.STATUS='completed' THEN 'previously-verified-completion' ELSE '' END,UTC_TIMESTAMP()
 FROM ALUMNI_ACCOUNT_ERASURE e JOIN ALUMNI_ACCOUNT_DELETION_REQUEST d ON d.REQUEST_ID=e.REQUEST_ID
 CROSS JOIN (SELECT 'backups' AS TARGET UNION ALL SELECT 'historical_files'
 UNION ALL SELECT 'external_data' UNION ALL SELECT 'other_identifiers') t;
