-- Record work in existing accounting originals; do not copy donor contact data.
CREATE TABLE IF NOT EXISTS ALUMNI_ERASURE_RECEIPT_WORK (
 REQUEST_ID BIGINT NOT NULL PRIMARY KEY,
 STATUS VARCHAR(20) NOT NULL DEFAULT 'unreviewed',
 ORIGINAL_STORAGE VARCHAR(30) NOT NULL DEFAULT '',
 EVIDENCE_REFERENCE VARCHAR(200) NOT NULL DEFAULT '',
 OPERATOR_SEQ INT NULL,
 UPDATED_AT DATETIME NOT NULL,
 COMPLETED_AT DATETIME NULL,
 CONSTRAINT FK_RECEIPT_WORK_REQUEST FOREIGN KEY (REQUEST_ID)
 REFERENCES ALUMNI_ACCOUNT_DELETION_REQUEST(REQUEST_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO ALUMNI_ERASURE_RECEIPT_WORK (REQUEST_ID,STATUS,EVIDENCE_REFERENCE,UPDATED_AT)
 SELECT REQUEST_ID,CASE WHEN STATUS='completed' THEN 'completed' ELSE 'unreviewed' END,
 CASE WHEN STATUS='completed' THEN 'previously-verified-completion' ELSE '' END,UTC_TIMESTAMP()
 FROM ALUMNI_ACCOUNT_DELETION_REQUEST;
