-- Preserve current/replaced managed profile paths even without a WEO_FILES row.
-- MariaDB 10.1.38; no source file or member row is deleted.
CREATE TABLE IF NOT EXISTS ALUMNI_PROFILE_FILE_HISTORY (
    USR_SEQ INT NOT NULL,
    URL_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    URL_PATH TEXT NOT NULL,
    RECORDED_AT DATETIME NOT NULL,
    PRIMARY KEY (USR_SEQ,URL_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO ALUMNI_PROFILE_FILE_HISTORY (USR_SEQ,URL_HASH,URL_PATH,RECORDED_AT)
SELECT USR_SEQ,SHA2(USR_PHOTO,256),USR_PHOTO,UTC_TIMESTAMP() FROM WEO_MEMBER
WHERE USR_PHOTO LIKE '/uploads/%' OR USR_PHOTO LIKE '/files/%' OR USR_PHOTO LIKE '/upload/%' OR USR_PHOTO LIKE '/old/upload/%';
INSERT IGNORE INTO ALUMNI_PROFILE_FILE_HISTORY (USR_SEQ,URL_HASH,URL_PATH,RECORDED_AT)
SELECT USR_SEQ,SHA2(USR_BIZ_CARD,256),USR_BIZ_CARD,UTC_TIMESTAMP() FROM WEO_MEMBER
WHERE USR_BIZ_CARD LIKE '/uploads/%' OR USR_BIZ_CARD LIKE '/files/%' OR USR_BIZ_CARD LIKE '/upload/%' OR USR_BIZ_CARD LIKE '/old/upload/%';
INSERT IGNORE INTO ALUMNI_PROFILE_FILE_HISTORY (USR_SEQ,URL_HASH,URL_PATH,RECORDED_AT)
SELECT USR_SEQ,SHA2(USR_THUMNAIL,256),USR_THUMNAIL,UTC_TIMESTAMP() FROM WEO_MEMBER
WHERE USR_THUMNAIL LIKE '/uploads/%' OR USR_THUMNAIL LIKE '/files/%' OR USR_THUMNAIL LIKE '/upload/%' OR USR_THUMNAIL LIKE '/old/upload/%';
