-- Access receipts contain no decrypted evidence or donor identifiers.
-- Independent of archive expiry; archive deletion must not delete access receipts.
CREATE TABLE IF NOT EXISTS ALUMNI_DONATION_ARCHIVE_ACCESS (
 ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 ARCHIVE_ID BIGINT NOT NULL,
 OPERATOR_SEQ INT NOT NULL,
 PURPOSE VARCHAR(30) NOT NULL,
 ACCESSED_AT DATETIME NOT NULL,
 KEY IDX_ARCHIVE_ACCESS (ARCHIVE_ID, ACCESSED_AT),
 KEY IDX_OPERATOR_ACCESS (OPERATOR_SEQ, ACCESSED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
