-- Additive cancellation capability. No existing request is restored or cancelled.
CREATE TABLE IF NOT EXISTS ALUMNI_ERASURE_CANCELLATION (
 REQUEST_ID BIGINT NOT NULL PRIMARY KEY,
 ORIGINAL_STATUS CHAR(3) NOT NULL,
 CANCEL_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
 RESTORE_BLOCKED TINYINT NOT NULL DEFAULT 0,
 STARTED_AT DATETIME NULL,
 CANCELLED_AT DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A subsequent change to a disabled member invalidates automatic restoration.
DROP TRIGGER IF EXISTS trg_erasure_cancel_restore_guard;
CREATE TRIGGER trg_erasure_cancel_restore_guard AFTER UPDATE ON WEO_MEMBER FOR EACH ROW
 UPDATE ALUMNI_ERASURE_CANCELLATION c JOIN ALUMNI_ACCOUNT_DELETION_REQUEST d ON d.REQUEST_ID=c.REQUEST_ID
 SET c.RESTORE_BLOCKED=1 WHERE d.USR_SEQ=NEW.USR_SEQ AND d.STATUS='pending' AND OLD.USR_STATUS='AAA';
