-- Operator attestation of external closure, bound to the current source rows.
-- No billing keys or account contact information are copied to this audit.
CREATE TABLE IF NOT EXISTS ALUMNI_ERASURE_SUBSCRIPTION_REVIEW (
    REQUEST_ID BIGINT NOT NULL,
    SUB_SEQ INT NOT NULL,
    SOURCE_FINGERPRINT CHAR(64) NOT NULL,
    PROVIDER_CLOSURE_OUTCOME VARCHAR(16) NOT NULL,
    EVIDENCE_REFERENCE VARCHAR(200) NOT NULL,
    OPERATOR_SEQ INT NOT NULL,
    REVIEWED_AT DATETIME NOT NULL,
    PRIMARY KEY (REQUEST_ID, SUB_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
