-- Synthetic TS09 data only. reset.sh discards every change.
-- Account 103 belongs to Android deletion tests; 104 is disposable for iOS TS12.
SET NAMES utf8mb4;

-- Generated by service.NewPasswordHasher().NewCredential and
-- service.MysqlNativePassword with Synthetic-password-09! (never a real password).
SET @legacy_password = '*439972C644A8B323B2B5201EB54F2AC0C74260CA';
SET @password_hash = '$argon2id$v=19$m=19456,t=2,p=1$HRfqqhFSe3iE3wHLF1wOhg$E3GIWeLQ9EU2ucs8b+zfs8lx0mLUEiUfZPtTSNG6XPQ';

INSERT INTO AUTH_IDENTITY_MIGRATION_RUN
    (RUN_ID, STATUS, SOURCE_FINGERPRINT, CONFLICT_COUNT, STARTED_AT, COMPLETED_AT, UPDATED_AT)
VALUES ('ts09-synthetic-run', 'APPLIED', REPEAT('a', 64), 0, NOW(), NOW(), NOW());
INSERT INTO AUTH_IDENTITY_MIGRATION_JOURNAL
    (RUN_ID, STEP_KEY, STATUS, STARTED_AT, APPLIED_AT, UPDATED_AT)
VALUES ('ts09-synthetic-run', 'synthetic-empty-backfill', 'APPLIED', NOW(), NOW(), NOW());

INSERT INTO WEO_MEMBER
    (USR_SEQ, USR_ID, USR_NAME, USR_PWD, USR_STATUS, USR_PHONE, USR_EMAIL, USR_FN, USR_DEPT, REG_DATE)
VALUES
    (100, 'e2e_member', '합성 동문', @legacy_password, 'CCC', '01000000003', 'member@example.test', 20, '영어', NOW()),
    (101, 'e2e_pending', '합성 대기', @legacy_password, 'BBB', '01000000004', 'pending@example.test', 20, '영어', NOW()),
    (102, 'e2e_friend', '합성 친구', @legacy_password, 'CCC', '01000000005', 'friend@example.test', 20, '영어', NOW()),
    (103, 'e2e_delete', '합성 삭제', @legacy_password, 'CCC', '01000000006', 'delete@example.test', 20, '영어', NOW()),
    (104, 'e2e_delete_ios', '합성 iOS 삭제', @legacy_password, 'CCC', '01000000007', 'delete-ios@example.test', 20, '영어', NOW());
INSERT INTO AUTH_ACCOUNT_STATE (ACCOUNT_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (100, 'ACTIVE', NOW(), NOW()), (101, 'ACTIVE', NOW(), NOW()), (102, 'ACTIVE', NOW(), NOW()),
    (103, 'ACTIVE', NOW(), NOW()), (104, 'ACTIVE', NOW(), NOW());
INSERT INTO AUTH_PHONE_CLAIM (CANONICAL_PHONE, ACCOUNT_ID, CREATED_AT)
VALUES ('01000000003', 100, NOW()), ('01000000004', 101, NOW()), ('01000000005', 102, NOW()),
    ('01000000006', 103, NOW()), ('01000000007', 104, NOW());
INSERT INTO AUTH_IDENTITY
    (IDENTITY_ID, ACCOUNT_ID, PROVIDER, SUBJECT_KEY, STATUS, VERIFIED_AT, CREATED_AT, UPDATED_AT)
VALUES
    (100, 100, 'LOCAL_USERNAME', 'e2e_member', 'ACTIVE', NOW(), NOW(), NOW()),
    (101, 101, 'LOCAL_USERNAME', 'e2e_pending', 'ACTIVE', NOW(), NOW(), NOW()),
    (102, 102, 'LOCAL_USERNAME', 'e2e_friend', 'ACTIVE', NOW(), NOW(), NOW()),
    (103, 103, 'LOCAL_USERNAME', 'e2e_delete', 'ACTIVE', NOW(), NOW(), NOW()),
    (104, 104, 'LOCAL_USERNAME', 'e2e_delete_ios', 'ACTIVE', NOW(), NOW(), NOW());
INSERT INTO AUTH_PASSWORD_CREDENTIAL
    (IDENTITY_ID, PROVIDER, ALGORITHM, PARAMETERS_TEXT, PASSWORD_HASH, STATUS, CREATED_AT, UPDATED_AT)
VALUES
    (100, 'LOCAL_USERNAME', 'ARGON2ID', 'm=19456,t=2,p=1', @password_hash, 'ACTIVE', NOW(), NOW()),
    (101, 'LOCAL_USERNAME', 'ARGON2ID', 'm=19456,t=2,p=1', @password_hash, 'ACTIVE', NOW(), NOW()),
    (102, 'LOCAL_USERNAME', 'ARGON2ID', 'm=19456,t=2,p=1', @password_hash, 'ACTIVE', NOW(), NOW()),
    (103, 'LOCAL_USERNAME', 'ARGON2ID', 'm=19456,t=2,p=1', @password_hash, 'ACTIVE', NOW(), NOW()),
    (104, 'LOCAL_USERNAME', 'ARGON2ID', 'm=19456,t=2,p=1', @password_hash, 'ACTIVE', NOW(), NOW());
INSERT INTO ALUMNI_VERIFICATION
    (USR_SEQ, STATUS, GRADUATION_YEAR, COHORT, DEPARTMENT, SUBMITTED_AT, REVIEWED_AT,
     APPROVED_GRADUATION_YEAR, APPROVED_COHORT, APPROVED_DEPARTMENT, CREATED_AT, UPDATED_AT)
VALUES
    (100, 'approved', 2007, '20', '영어', NOW(), NOW(), 2007, '20', '영어', NOW(), NOW()),
    (101, 'pending', 2007, '20', '영어', NOW(), NULL, NULL, NULL, NULL, NOW(), NOW()),
    (102, 'approved', 2007, '20', '영어', NOW(), NOW(), 2007, '20', '영어', NOW(), NOW()),
    (103, 'approved', 2007, '20', '영어', NOW(), NOW(), 2007, '20', '영어', NOW(), NOW()),
    (104, 'approved', 2007, '20', '영어', NOW(), NOW(), 2007, '20', '영어', NOW(), NOW());

-- The signup number is in the alumni roster only, never a member/phone claim.
INSERT INTO FUNDAMENTAL_NUMBERS (FN, FN_GYEAR, FN_DEPT, REG_DATE)
VALUES (20, 2007, '영어', NOW());
INSERT INTO FUNDAMENTAL_MEMBER
    (FM_SEQ, USR_SEQ, FM_NAME, FM_FN, FM_DEPT, FM_PHONE, FM_EMAIL, REG_DATE)
VALUES (200, NULL, '합성 가입자', 20, '영어', '01000000002', 'signup@example.test', NOW());

INSERT INTO WEO_BOARDBBS
    (SEQ, GATE, USR_SEQ, REG_ID, REG_NAME, SUBJECT, CONTENTS, CONTENTS_MD, CONTENT_FORMAT,
     CONTENTS_TYPE, SUMMARY, OPEN_YN, REG_DATE, EDT_DATE)
VALUES
    (900, 'NOTICE', 100, 'e2e_member', '합성 동문', '합성 동문 모임 안내',
     TO_BASE64('<p>로컬 E2E 테스트용 모임 안내입니다.</p>'), '로컬 E2E 테스트용 모임 안내입니다.',
     'MARKDOWN', 'H', '로컬 E2E 테스트용 모임 안내입니다.', 'Y', NOW(), NOW()),
    (901, 'NOTICE', 102, 'e2e_friend', '합성 친구', '합성 동문 소식',
     TO_BASE64('<p>합성 데이터로 피드 상세 화면을 확인합니다.</p>'), '합성 데이터로 피드 상세 화면을 확인합니다.',
     'MARKDOWN', 'H', '합성 데이터로 피드 상세 화면을 확인합니다.', 'Y', NOW(), NOW());

INSERT INTO ALUMNI_MESSAGE
    (AM_SEQ, AM_SENDER_SEQ, AM_RECVR_SEQ, AM_CLIENT_MESSAGE_ID, AM_CONTENT, AM_READ_YN, REG_DATE, READ_DATE)
VALUES
    (800, 100, 102, 'ts09-seed-message-1', '안녕하세요. 합성 테스트 쪽지입니다.', 'Y', UTC_TIMESTAMP() - INTERVAL 2 MINUTE, UTC_TIMESTAMP()),
    (801, 102, 100, 'ts09-seed-message-2', '반갑습니다. 답장 테스트를 진행해 주세요.', 'N', UTC_TIMESTAMP() - INTERVAL 1 MINUTE, NULL);

INSERT INTO app_settings (AS_KEY, AS_VALUE, AS_DESCRIPTION, AS_PUBLIC, UPDATED_AT)
VALUES
    ('app_update_policy_ios', '{"forceEnabled":false,"minBuild":0,"recommendEnabled":false,"recommendedBuild":0,"minOsVersion":"17.0","storeUrl":""}', 'Synthetic iOS E2E policy', 'Y', NOW()),
    ('app_update_policy_android', '{"forceEnabled":false,"minBuild":0,"recommendEnabled":false,"recommendedBuild":0,"minOsVersion":"26","storeUrl":""}', 'Synthetic Android E2E policy', 'Y', NOW())
ON DUPLICATE KEY UPDATE AS_VALUE = VALUES(AS_VALUE), AS_PUBLIC = 'Y', UPDATED_AT = NOW();
